#ifndef PLUGIN_GLOBAL_H
#define PLUGIN_GLOBAL_H

#if defined(INTERFACEPLUGIN_LIBRARY)
#define INTERFACEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define INTERFACEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_GLOBAL_H
