INTERFACE_SRC_NAME=interface
INTERFACE_LIB_NAME=PluginInterface

INCLUDEPATH += $$TOP_SRCDIR/plugins/$${INTERFACE_SRC_NAME}
DEPENDPATH += $$TOP_SRCDIR/plugins/$${INTERFACE_SRC_NAME}

CONFIG += rtti c++17

PRECOMPILED_HEADER = pch.h
CONFIG += precompile_header
