SRC_ROOT_DIR=$${PWD}

APP_DIR=$${BUILD_ROOT_DIR}
LIB_DIR=$${BUILD_ROOT_DIR}/lib
PLUGINS_DIR=$${BUILD_ROOT_DIR}/plugins

INTERFACE_SRC_NAME=interface
INTERFACE_LIB_NAME=PluginInterface

INCLUDEPATH += $${SRC_ROOT_DIR}/plugins/$${INTERFACE_SRC_NAME}
DEPENDPATH += $${SRC_ROOT_DIR}/plugins/$${INTERFACE_SRC_NAME}

CONFIG += rtti c++17

PRECOMPILED_HEADER = pch.h
#DEFINES += USING_PCH
CONFIG += precompile_header
