Document: emg-diagnostics
Title: Debian emg-diagnostics Manual
Author: <insert document author here>
Abstract: This manual describes what emg-diagnostics is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/emg-diagnostics/emg-diagnostics.sgml.gz

Format: postscript
Files: /usr/share/doc/emg-diagnostics/emg-diagnostics.ps.gz

Format: text
Files: /usr/share/doc/emg-diagnostics/emg-diagnostics.text.gz

Format: HTML
Index: /usr/share/doc/emg-diagnostics/html/index.html
Files: /usr/share/doc/emg-diagnostics/html/*.html
