#ifndef UECG_VERSION_H
#define UECG_VERSION_H

#define UECG_VERSION_STRING "0.0.1"
#define UECG_VERSION_MAJOR 0
#define UECG_VERSION_MINOR 0
#define UECG_VERSION_RELEASE 1
#define UECG_MAKE_VERSION( a,b,c ) (((a) << 16) | ((b) << 8) | (c))

#define UECG_VERSION \
  UECG_MAKE_VERSION(UECG_VERSION_MAJOR,UECG_VERSION_MINOR,UECG_VERSION_RELEASE)

#define UECG_IS_VERSION(a,b,c) ( UECG_VERSION >= UECG_MAKE_VERSION(a,b,c) )

#endif // UECG_VERSION_H
